services:

  valkey:
    image: valkey/valkey:7.2.5-alpine
    container_name: valkey
    restart: unless-stopped
    command: >
      valkey-server
      --appendonly yes
    volumes:
      - valkey_data:/data
    networks:
      - dnsnet

  dns-proxy:
    build: .
    container_name: dns-proxy
    restart: unless-stopped
    depends_on:
      - valkey
    volumes:
      - ./config:/app/config
      - ./certs:/app/certs
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8080:8080"
    networks:
      - dnsnet

  coredns:
    image: coredns/coredns:1.14.1
    container_name: coredns
    restart: unless-stopped
    depends_on:
      - dns-proxy
    volumes:
      - ./Corefile:/Corefile
      - ./certs:/certs
    ports:
      - "853:853/tcp"     # DoT
      - "443:443/tcp"     # DoH
    networks:
      - dnsnet

volumes:
  valkey_data:

networks:
  dnsnet:
